######################################################################
#
# File name : pipeline_adder_tb_compile.do
# Created on: Tue Oct 10 21:17:32 +0800 2023
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"pipeline_adder_tb_time_impl.v" \
"../../../../../../../src/d_ff.v" \
"../../../../../../../src/pipeline_adder.v" \
"../../../../../../../src/pipeline_adder_tb.v" \


quit -force

